substitutions:
  # Names
  name: dht-sensor
  friendly_name: DHT Sensor
  # Wifi
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  # Configs
  sensor_update_interval: 10s


esphome:
  name: "${name}"
  # Friendly names are used where appropriate in Home Assistant
  friendly_name: "${friendly_name}"
  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  name_add_mac_suffix: true

rp2040:
  board: rpipicow

# Enable logging
logger:

# Enable Home Assistant API. Used by esphome cli and esphome dashboard
# to connect to the device.
api:
  password: ""

# Enable Over-The-Air updates
ota:
  - platform: esphome

wifi:
  ssid: "${wifi_ssid}"
  password: "${wifi_password}"

# Temperature and humidity sensor
sensor:
  - platform: dht
    model: DHT22
    pin: 
      number: GPIO5
      mode:
        input: true
        pullup: false
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
      accuracy_decimals: 1
    update_interval: "${sensor_update_interval}"

# status led
status_led:
  pin: LED