substitutions:
  # Names
  name: example-sensor
  friendly_name: Example Sensor
  # Wifi
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  # Configs
  sensor_update_interval: 10s

# Use the DHT sensor as a template sensor
<<: !include .base-sensor.yaml
