esphome:
  name: livingroom

rp2040:
  board: rpipicow

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot in case wifi connection fails
  ap: {}

# Temperature and humidity sensor
sensor:
  - platform: dht
    pin: 
      number: GPIO5
      mode:
        input: true
        pullup: true
    temperature:
      name: "Living Room Temperature"
    humidity:
      name: "Living Room Humidity"
      accuracy_decimals: 1
    update_interval: 10s

# status led
status_led:
  pin: LED